//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grow.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GROWEntities : DbContext
    {
        public GROWEntities()
            : base("name=GROWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Ligth> Ligths { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Seed> Seeds { get; set; }
        public virtual DbSet<Sex> Sexes { get; set; }
        public virtual DbSet<TypeFarm> TypeFarms { get; set; }
        public virtual DbSet<TypeLight> TypeLights { get; set; }
        public virtual DbSet<TypeSeed> TypeSeeds { get; set; }
        public virtual DbSet<Variaty> Variaties { get; set; }
        public virtual DbSet<VariatySeed> VariatySeeds { get; set; }
    }
}
