//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grow.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public long id { get; set; }
        public string alias { get; set; }
        public long idSeed { get; set; }
        public long idFarm { get; set; }
        public Nullable<System.DateTime> dateGermination { get; set; }
        public Nullable<System.DateTime> dateGrow { get; set; }
        public Nullable<System.DateTime> dateFlow { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual Seed Seed { get; set; }
    }
}
