//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grow.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seed()
        {
            this.Plants = new HashSet<Plant>();
            this.VariatySeeds = new HashSet<VariatySeed>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public long idBank { get; set; }
        public string genetic { get; set; }
        public Nullable<int> daysGrow { get; set; }
        public Nullable<int> daysFlow { get; set; }
        public Nullable<int> heightIndoor { get; set; }
        public Nullable<int> heightOutdoor { get; set; }
        public long idTypeSeed { get; set; }
        public long idSex { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual TypeSeed TypeSeed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariatySeed> VariatySeeds { get; set; }
    }
}
