//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grow.Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariatySeed
    {
        public long id { get; set; }
        public long idSeed { get; set; }
        public long idVariety { get; set; }
        public int porcentage { get; set; }
    
        public virtual Seed Seed { get; set; }
        public virtual Variaty Variaty { get; set; }
    }
}
